// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
lv_obj_t * ui_main;
lv_obj_t * ui_separator;
lv_obj_t * ui_tempMain;
lv_obj_t * ui_rhMain;
lv_obj_t * ui_pMain;
lv_obj_t * ui_pageCNT0;
lv_obj_t * ui_labeltimeformat;
void ui_event_tfChangeBTN(lv_event_t * e);
lv_obj_t * ui_tfChangeBTN;
lv_obj_t * ui_popuptimeformat;
void ui_event_amFormat(lv_event_t * e);
lv_obj_t * ui_amFormat;
lv_obj_t * ui_AMlabel;
void ui_event_pmFormat(lv_event_t * e);
lv_obj_t * ui_pmFormat;
lv_obj_t * ui_PMlabel;
void ui_event_timeButton(lv_event_t * e);
lv_obj_t * ui_timeButton;
lv_obj_t * ui_lableTime;
lv_obj_t * ui_lableDate;
void ui_event_dateButton(lv_event_t * e);
lv_obj_t * ui_dateButton;
// CUSTOM VARIABLES


// SCREEN: ui_tempSCR
void ui_tempSCR_screen_init(void);
void ui_event_tempSCR(lv_event_t * e);
lv_obj_t * ui_tempSCR;
lv_obj_t * ui_tempCH;
lv_obj_t * ui_pageCNT1;
lv_obj_t * ui_valTempSCR1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_tempStaticCH;
lv_obj_t * ui_TempStaticPeriod;
void ui_event_tempArchive(lv_event_t * e);
lv_obj_t * ui_tempArchive;
lv_obj_t * ui_Label20;
// CUSTOM VARIABLES


// SCREEN: ui_humidSCR
void ui_humidSCR_screen_init(void);
void ui_event_humidSCR(lv_event_t * e);
lv_obj_t * ui_humidSCR;
lv_obj_t * ui_humidCH;
lv_obj_t * ui_pageCNT2;
lv_obj_t * ui_valHumidSCR2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_humidStaticCH;
lv_obj_t * ui_HumidStaticPeriod;
void ui_event_humidArchive(lv_event_t * e);
lv_obj_t * ui_humidArchive;
lv_obj_t * ui_Label22;
// CUSTOM VARIABLES


// SCREEN: ui_pressSCR
void ui_pressSCR_screen_init(void);
void ui_event_pressSCR(lv_event_t * e);
lv_obj_t * ui_pressSCR;
lv_obj_t * ui_pressCH;
lv_obj_t * ui_pageCNT3;
lv_obj_t * ui_valPressSCR3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_pressStaticCH;
lv_obj_t * ui_PressStaticPeriod;
void ui_event_pressArchive(lv_event_t * e);
lv_obj_t * ui_pressArchive;
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES


// SCREEN: ui_dateAndtimeSCR
void ui_dateAndtimeSCR_screen_init(void);
lv_obj_t * ui_dateAndtimeSCR;
void ui_event_timeOK(lv_event_t * e);
lv_obj_t * ui_timeOK;
lv_obj_t * ui_textOKh;
void ui_event_dateOK(lv_event_t * e);
lv_obj_t * ui_dateOK;
lv_obj_t * ui_textOKh1;
void ui_event_timeAndDateCANCEL(lv_event_t * e);
lv_obj_t * ui_timeAndDateCANCEL;
lv_obj_t * ui_textCancel;
lv_obj_t * ui_lableTimeChange;
lv_obj_t * ui_lableDateChange;
lv_obj_t * ui_ContainerTime;
void ui_event_hourUP(lv_event_t * e);
lv_obj_t * ui_hourUP;
lv_obj_t * ui_Label7;
void ui_event_hourDOWN(lv_event_t * e);
lv_obj_t * ui_hourDOWN;
lv_obj_t * ui_Label1;
void ui_event_minuteUP(lv_event_t * e);
lv_obj_t * ui_minuteUP;
lv_obj_t * ui_Label4;
void ui_event_minuteDOWN(lv_event_t * e);
lv_obj_t * ui_minuteDOWN;
lv_obj_t * ui_Label3;
void ui_event_secondUP(lv_event_t * e);
lv_obj_t * ui_secondUP;
lv_obj_t * ui_Label8;
void ui_event_secondDOWN(lv_event_t * e);
lv_obj_t * ui_secondDOWN;
lv_obj_t * ui_Label9;
void ui_event_btnsavetime(lv_event_t * e);
lv_obj_t * ui_btnsavetime;
lv_obj_t * ui_Label10;
void ui_event_btncancelChoose(lv_event_t * e);
lv_obj_t * ui_btncancelChoose;
lv_obj_t * ui_Label11;
lv_obj_t * ui_spinboxSeconds;
lv_obj_t * ui_spinboxMinutes;
lv_obj_t * ui_spinboxHours;
lv_obj_t * ui_ContainerDate;
void ui_event_hourUP1(lv_event_t * e);
lv_obj_t * ui_hourUP1;
lv_obj_t * ui_Label12;
void ui_event_hourDOWN1(lv_event_t * e);
lv_obj_t * ui_hourDOWN1;
lv_obj_t * ui_Label13;
void ui_event_minuteUP1(lv_event_t * e);
lv_obj_t * ui_minuteUP1;
lv_obj_t * ui_Label14;
void ui_event_minuteDOWN1(lv_event_t * e);
lv_obj_t * ui_minuteDOWN1;
lv_obj_t * ui_Label15;
void ui_event_secondUP1(lv_event_t * e);
lv_obj_t * ui_secondUP1;
lv_obj_t * ui_Label16;
void ui_event_secondDOWN1(lv_event_t * e);
lv_obj_t * ui_secondDOWN1;
lv_obj_t * ui_Label17;
void ui_event_btnsavedate(lv_event_t * e);
lv_obj_t * ui_btnsavedate;
lv_obj_t * ui_Label18;
void ui_event_btncancelChoose1(lv_event_t * e);
lv_obj_t * ui_btncancelChoose1;
lv_obj_t * ui_Label19;
lv_obj_t * ui_spinboxYear;
lv_obj_t * ui_spinboxMonth;
lv_obj_t * ui_spinboxDay;
lv_obj_t * ui_ContainerTimeStatic;
void ui_event_hourUP8(lv_event_t * e);
lv_obj_t * ui_hourUP8;
lv_obj_t * ui_Label76;
void ui_event_hourDOWN8(lv_event_t * e);
lv_obj_t * ui_hourDOWN8;
lv_obj_t * ui_Label77;
void ui_event_minuteUP8(lv_event_t * e);
lv_obj_t * ui_minuteUP8;
lv_obj_t * ui_Label69;
void ui_event_minuteDOWN8(lv_event_t * e);
lv_obj_t * ui_minuteDOWN8;
lv_obj_t * ui_Label70;
void ui_event_secondUP8(lv_event_t * e);
lv_obj_t * ui_secondUP8;
lv_obj_t * ui_Label71;
void ui_event_secondDOWN8(lv_event_t * e);
lv_obj_t * ui_secondDOWN8;
lv_obj_t * ui_Label72;
void ui_event_btnsavetime4(lv_event_t * e);
lv_obj_t * ui_btnsavetime4;
lv_obj_t * ui_Label73;
void ui_event_btncancelChoose8(lv_event_t * e);
lv_obj_t * ui_btncancelChoose8;
lv_obj_t * ui_Label74;
lv_obj_t * ui_startSecond;
lv_obj_t * ui_startMinute;
lv_obj_t * ui_startHour;
lv_obj_t * ui_Label68;
lv_obj_t * ui_lableTimeChange1;
lv_obj_t * ui_ContainerDateStatic;
void ui_event_hourUP9(lv_event_t * e);
lv_obj_t * ui_hourUP9;
lv_obj_t * ui_Label75;
void ui_event_hourDOWN9(lv_event_t * e);
lv_obj_t * ui_hourDOWN9;
lv_obj_t * ui_Label78;
void ui_event_minuteUP9(lv_event_t * e);
lv_obj_t * ui_minuteUP9;
lv_obj_t * ui_Label79;
void ui_event_minuteDOWN9(lv_event_t * e);
lv_obj_t * ui_minuteDOWN9;
lv_obj_t * ui_Label80;
void ui_event_secondUP9(lv_event_t * e);
lv_obj_t * ui_secondUP9;
lv_obj_t * ui_Label81;
void ui_event_secondDOWN9(lv_event_t * e);
lv_obj_t * ui_secondDOWN9;
lv_obj_t * ui_Label82;
void ui_event_btnsavedateStatic(lv_event_t * e);
lv_obj_t * ui_btnsavedateStatic;
lv_obj_t * ui_Label83;
void ui_event_btncancelChooseStatic(lv_event_t * e);
lv_obj_t * ui_btncancelChooseStatic;
lv_obj_t * ui_Label84;
lv_obj_t * ui_startYear;
lv_obj_t * ui_startMonth;
lv_obj_t * ui_startDay;
lv_obj_t * ui_Label85;
lv_obj_t * ui_lableDateChange4;

uint8_t tempArch_flag = 0;
uint8_t humidArch_flag = 0;
uint8_t pressArch_flag = 0;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_tempSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tempSCR_screen_init);
    }
}

void ui_event_tfChangeBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_popuptimeformat, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_amFormat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_labeltimeformat, target, "AM", "AM");
        amTochange(e);
    }
}

void ui_event_pmFormat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_labeltimeformat, target, "PM", "PM");
        pmTochange(e);
    }
}

void ui_event_timeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_dateAndtimeSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dateAndtimeSCR_screen_init);
        _ui_flag_modify(ui_ContainerTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_dateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerDate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_screen_change(&ui_dateAndtimeSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dateAndtimeSCR_screen_init);
    }
}

void ui_event_tempSCR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_humidSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_humidSCR_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
    }
}

void ui_event_tempArchive(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
		if(tempArch_flag == 1){
        	_ui_flag_modify(ui_TempStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_tempStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_tempCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}
		else{
        	_ui_screen_change(&ui_dateAndtimeSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dateAndtimeSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}

		tempArch_need_flag(e);
    }
}

void ui_event_humidSCR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_pressSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pressSCR_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_tempSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tempSCR_screen_init);
    }
}

void ui_event_humidArchive(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
		if(humidArch_flag == 1){
        	_ui_flag_modify(ui_HumidStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_humidStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_humidCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}
		else{
        	_ui_screen_change(&ui_dateAndtimeSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dateAndtimeSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}

        humidArch_need_flag(e);
    }
}

void ui_event_pressSCR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_humidSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_humidSCR_screen_init);
    }
}

void ui_event_pressArchive(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
		if(pressArch_flag == 1){
        	_ui_flag_modify(ui_PressStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_pressStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_pressCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}
		else{
        	_ui_screen_change(&ui_dateAndtimeSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_dateAndtimeSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
		}

        pressArch_need_flag(e);
    }
}

void ui_event_timeOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_timeOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_timeAndDateCANCEL, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_dateOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_dateOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_timeAndDateCANCEL, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_timeAndDateCANCEL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_timeOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_timeAndDateCANCEL, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_dateOK, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_hourUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxHours, 1);
    }
}

void ui_event_hourDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxHours, -1);
    }
}

void ui_event_minuteUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxMinutes, 1);
    }
}

void ui_event_minuteDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxMinutes, -1);
    }
}

void ui_event_secondUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxSeconds, 1);
    }
}

void ui_event_secondDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxSeconds, -1);
    }
}

void ui_event_btnsavetime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        save_time_event(e);
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_btncancelChoose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_ContainerTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_hourUP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxDay, 1);
    }
}

void ui_event_hourDOWN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxDay, -1);
    }
}

void ui_event_minuteUP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxMonth, 1);
    }
}

void ui_event_minuteDOWN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxMonth, -1);
    }
}

void ui_event_secondUP1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxYear, 1);
    }
}

void ui_event_secondDOWN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_spinboxYear, -1);
    }
}

void ui_event_btnsavedate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        save_date_event(e);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerDate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
    }
}

void ui_event_btncancelChoose1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_ContainerDate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_hourUP8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startHour, 1);
    }
}

void ui_event_hourDOWN8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startHour, -1);
    }
}

void ui_event_minuteUP8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startMinute, 1);
    }
}

void ui_event_minuteDOWN8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startMinute, -1);
    }
}

void ui_event_secondUP8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startSecond, 1);
    }
}

void ui_event_secondDOWN8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startSecond, -1);
    }
}

void ui_event_btnsavetime4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        init_static_time_save(e);
        _ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_btncancelChoose8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
		if(tempArch_flag == 1){
        	_ui_screen_change(&ui_tempSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tempSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
			tempArch_need_flag(e);
		}
		else if(humidArch_flag == 1){
        	_ui_screen_change(&ui_humidSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_humidSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
			humidArch_need_flag(e);
		}
		else if(pressArch_flag == 1){
        	_ui_screen_change(&ui_pressSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pressSCR_screen_init);
        	_ui_flag_modify(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
			pressArch_need_flag(e);
		}
    }
}

void ui_event_hourUP9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startDay, 1);
    }
}

void ui_event_hourDOWN9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startDay, -1);
    }
}

void ui_event_minuteUP9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startMonth, 1);
    }
}

void ui_event_minuteDOWN9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startMonth, -1);
    }
}

void ui_event_secondUP9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startYear, 1);
    }
}

void ui_event_secondDOWN9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_startYear, -1);
    }
}

void ui_event_btnsavedateStatic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        init_static_date_save(e);
		if(tempArch_flag == 1){
        	_ui_screen_change(&ui_tempSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tempSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_TempStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_tempStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_tempCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
		}
		else if(humidArch_flag == 1){
        	_ui_screen_change(&ui_humidSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_humidSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_HumidStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_humidStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_humidCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
		}
		else if(pressArch_flag == 1){
        	_ui_screen_change(&ui_pressSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pressSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	_ui_flag_modify(ui_PressStaticPeriod, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_pressStaticCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        	_ui_flag_modify(ui_pressCH, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
		}
    }
}

void ui_event_btncancelChooseStatic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
		if(tempArch_flag == 1){
        	_ui_screen_change(&ui_tempSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_tempSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	tempArch_need_flag(e);
		}
		else if(humidArch_flag == 1){
        	_ui_screen_change(&ui_humidSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_humidSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	humidArch_need_flag(e);
		}
		else if(pressArch_flag == 1){
        	_ui_screen_change(&ui_pressSCR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pressSCR_screen_init);
        	_ui_flag_modify(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        	pressArch_need_flag(e);
		}
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_tempSCR_screen_init();
    ui_humidSCR_screen_init();
    ui_pressSCR_screen_init();
    ui_dateAndtimeSCR_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
