// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_dateAndtimeSCR_screen_init(void)
{
    ui_dateAndtimeSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dateAndtimeSCR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_dateAndtimeSCR, LV_SCROLLBAR_MODE_OFF);
    ui_object_set_themeable_style_property(ui_dateAndtimeSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_dateAndtimeSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);
    ui_object_set_themeable_style_property(ui_dateAndtimeSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_black);
    lv_obj_set_style_bg_grad_dir(ui_dateAndtimeSCR, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeOK = lv_btn_create(ui_dateAndtimeSCR);
    lv_obj_set_width(ui_timeOK, 70);
    lv_obj_set_height(ui_timeOK, 40);
    lv_obj_set_x(ui_timeOK, 80);
    lv_obj_set_y(ui_timeOK, 75);
    lv_obj_set_align(ui_timeOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timeOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_timeOK, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_timeOK, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_textOKh = lv_label_create(ui_timeOK);
    lv_obj_set_width(ui_textOKh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textOKh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textOKh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textOKh, "OK");
    ui_object_set_themeable_style_property(ui_textOKh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_textOKh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);
    ui_object_set_themeable_style_property(ui_textOKh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_textOKh, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_dateOK = lv_btn_create(ui_dateAndtimeSCR);
    lv_obj_set_width(ui_dateOK, 70);
    lv_obj_set_height(ui_dateOK, 40);
    lv_obj_set_x(ui_dateOK, 80);
    lv_obj_set_y(ui_dateOK, 75);
    lv_obj_set_align(ui_dateOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dateOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dateOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_dateOK, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_dateOK, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_textOKh1 = lv_label_create(ui_dateOK);
    lv_obj_set_width(ui_textOKh1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textOKh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textOKh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textOKh1, "OK");
    ui_object_set_themeable_style_property(ui_textOKh1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_textOKh1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);
    ui_object_set_themeable_style_property(ui_textOKh1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_textOKh1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_timeAndDateCANCEL = lv_btn_create(ui_dateAndtimeSCR);
    lv_obj_set_width(ui_timeAndDateCANCEL, 70);
    lv_obj_set_height(ui_timeAndDateCANCEL, 40);
    lv_obj_set_x(ui_timeAndDateCANCEL, -80);
    lv_obj_set_y(ui_timeAndDateCANCEL, 75);
    lv_obj_set_align(ui_timeAndDateCANCEL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeAndDateCANCEL, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_timeAndDateCANCEL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_timeAndDateCANCEL, LV_SCROLLBAR_MODE_OFF);
    ui_object_set_themeable_style_property(ui_timeAndDateCANCEL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_timeAndDateCANCEL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_textCancel = lv_label_create(ui_timeAndDateCANCEL);
    lv_obj_set_width(ui_textCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_textCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textCancel, "CANCEL");
    ui_object_set_themeable_style_property(ui_textCancel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_textCancel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);
    ui_object_set_themeable_style_property(ui_textCancel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_textCancel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_lableTimeChange = lv_label_create(ui_dateAndtimeSCR);
    lv_obj_set_width(ui_lableTimeChange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableTimeChange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableTimeChange, -21);
    lv_obj_set_y(ui_lableTimeChange, -93);
    lv_obj_set_align(ui_lableTimeChange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableTimeChange,
                      "             HOURS       MINUTES     SECONDS\n           ------------      ---------------    --------------");
    lv_obj_add_flag(ui_lableTimeChange, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_lableDateChange = lv_label_create(ui_dateAndtimeSCR);
    lv_obj_set_width(ui_lableDateChange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableDateChange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableDateChange, 0);
    lv_obj_set_y(ui_lableDateChange, -94);
    lv_obj_set_align(ui_lableDateChange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableDateChange,
                      "  DAY          MONTH         YEAR\n---------        ------------      -----------");
    lv_obj_add_flag(ui_lableDateChange, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ContainerTime = lv_obj_create(ui_dateAndtimeSCR);
    lv_obj_remove_style_all(ui_ContainerTime);
    lv_obj_set_width(ui_ContainerTime, 261);
    lv_obj_set_height(ui_ContainerTime, 192);
    lv_obj_set_align(ui_ContainerTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourUP = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_hourUP, 30);
    lv_obj_set_height(ui_hourUP, 35);
    lv_obj_set_x(ui_hourUP, -101);
    lv_obj_set_y(ui_hourUP, -15);
    lv_obj_set_align(ui_hourUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label7 = lv_label_create(ui_hourUP);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "UP");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_hourDOWN = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_hourDOWN, 30);
    lv_obj_set_height(ui_hourDOWN, 35);
    lv_obj_set_x(ui_hourDOWN, -67);
    lv_obj_set_y(ui_hourDOWN, -15);
    lv_obj_set_align(ui_hourDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label1 = lv_label_create(ui_hourDOWN);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "DN");
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteUP = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_minuteUP, 30);
    lv_obj_set_height(ui_minuteUP, 35);
    lv_obj_set_x(ui_minuteUP, -17);
    lv_obj_set_y(ui_minuteUP, -15);
    lv_obj_set_align(ui_minuteUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label4 = lv_label_create(ui_minuteUP);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "UP");
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteDOWN = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_minuteDOWN, 30);
    lv_obj_set_height(ui_minuteDOWN, 35);
    lv_obj_set_x(ui_minuteDOWN, 16);
    lv_obj_set_y(ui_minuteDOWN, -15);
    lv_obj_set_align(ui_minuteDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label3 = lv_label_create(ui_minuteDOWN);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "DN");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondUP = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_secondUP, 30);
    lv_obj_set_height(ui_secondUP, 35);
    lv_obj_set_x(ui_secondUP, 68);
    lv_obj_set_y(ui_secondUP, -15);
    lv_obj_set_align(ui_secondUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondUP, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label8 = lv_label_create(ui_secondUP);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "UP");
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondDOWN = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_secondDOWN, 30);
    lv_obj_set_height(ui_secondDOWN, 35);
    lv_obj_set_x(ui_secondDOWN, 101);
    lv_obj_set_y(ui_secondDOWN, -15);
    lv_obj_set_align(ui_secondDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondDOWN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label9 = lv_label_create(ui_secondDOWN);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "DN");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btnsavetime = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_btnsavetime, 100);
    lv_obj_set_height(ui_btnsavetime, 32);
    lv_obj_set_x(ui_btnsavetime, 0);
    lv_obj_set_y(ui_btnsavetime, 38);
    lv_obj_set_align(ui_btnsavetime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsavetime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnsavetime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btnsavetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btnsavetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label10 = lv_label_create(ui_btnsavetime);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SAVE");
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btncancelChoose = lv_btn_create(ui_ContainerTime);
    lv_obj_set_width(ui_btncancelChoose, 100);
    lv_obj_set_height(ui_btncancelChoose, 32);
    lv_obj_set_x(ui_btncancelChoose, 0);
    lv_obj_set_y(ui_btncancelChoose, 80);
    lv_obj_set_align(ui_btncancelChoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncancelChoose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncancelChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btncancelChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btncancelChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label11 = lv_label_create(ui_btncancelChoose);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 2);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "CANCEL");
    ui_object_set_themeable_style_property(ui_Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_spinboxSeconds = lv_spinbox_create(ui_ContainerTime);
    lv_obj_set_width(ui_spinboxSeconds, 70);
    lv_obj_set_height(ui_spinboxSeconds, 42);
    lv_obj_set_x(ui_spinboxSeconds, 84);
    lv_obj_set_y(ui_spinboxSeconds, -58);
    lv_obj_set_align(ui_spinboxSeconds, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxSeconds, 2, 2);
    lv_spinbox_set_range(ui_spinboxSeconds, 0, 59);
    lv_spinbox_set_cursor_pos(ui_spinboxSeconds, 1 - 1);
    lv_spinbox_set_value(ui_spinboxSeconds, 2);
    ui_object_set_themeable_style_property(ui_spinboxSeconds, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxSeconds, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_spinboxMinutes = lv_spinbox_create(ui_ContainerTime);
    lv_obj_set_width(ui_spinboxMinutes, 70);
    lv_obj_set_height(ui_spinboxMinutes, 42);
    lv_obj_set_x(ui_spinboxMinutes, 0);
    lv_obj_set_y(ui_spinboxMinutes, -58);
    lv_obj_set_align(ui_spinboxMinutes, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxMinutes, 2, 2);
    lv_spinbox_set_range(ui_spinboxMinutes, 0, 59);
    lv_spinbox_set_cursor_pos(ui_spinboxMinutes, 1 - 1);
    lv_spinbox_set_value(ui_spinboxMinutes, 2);
    ui_object_set_themeable_style_property(ui_spinboxMinutes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxMinutes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_spinboxHours = lv_spinbox_create(ui_ContainerTime);
    lv_obj_set_width(ui_spinboxHours, 70);
    lv_obj_set_height(ui_spinboxHours, 42);
    lv_obj_set_x(ui_spinboxHours, -84);
    lv_obj_set_y(ui_spinboxHours, -58);
    lv_obj_set_align(ui_spinboxHours, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxHours, 2, 2);
    lv_spinbox_set_range(ui_spinboxHours, 1, 12);
    lv_spinbox_set_cursor_pos(ui_spinboxHours, 1 - 1);
    lv_spinbox_set_value(ui_spinboxHours, 2);
    ui_object_set_themeable_style_property(ui_spinboxHours, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxHours, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_ContainerDate = lv_obj_create(ui_dateAndtimeSCR);
    lv_obj_remove_style_all(ui_ContainerDate);
    lv_obj_set_width(ui_ContainerDate, 261);
    lv_obj_set_height(ui_ContainerDate, 192);
    lv_obj_set_align(ui_ContainerDate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerDate, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerDate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourUP1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_hourUP1, 30);
    lv_obj_set_height(ui_hourUP1, 35);
    lv_obj_set_x(ui_hourUP1, -101);
    lv_obj_set_y(ui_hourUP1, -15);
    lv_obj_set_align(ui_hourUP1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourUP1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourUP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label12 = lv_label_create(ui_hourUP1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "UP");
    ui_object_set_themeable_style_property(ui_Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_hourDOWN1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_hourDOWN1, 30);
    lv_obj_set_height(ui_hourDOWN1, 35);
    lv_obj_set_x(ui_hourDOWN1, -67);
    lv_obj_set_y(ui_hourDOWN1, -15);
    lv_obj_set_align(ui_hourDOWN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourDOWN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourDOWN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label13 = lv_label_create(ui_hourDOWN1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "DN");
    ui_object_set_themeable_style_property(ui_Label13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteUP1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_minuteUP1, 30);
    lv_obj_set_height(ui_minuteUP1, 35);
    lv_obj_set_x(ui_minuteUP1, -17);
    lv_obj_set_y(ui_minuteUP1, -15);
    lv_obj_set_align(ui_minuteUP1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteUP1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteUP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label14 = lv_label_create(ui_minuteUP1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "UP");
    ui_object_set_themeable_style_property(ui_Label14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteDOWN1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_minuteDOWN1, 30);
    lv_obj_set_height(ui_minuteDOWN1, 35);
    lv_obj_set_x(ui_minuteDOWN1, 16);
    lv_obj_set_y(ui_minuteDOWN1, -15);
    lv_obj_set_align(ui_minuteDOWN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteDOWN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteDOWN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label15 = lv_label_create(ui_minuteDOWN1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "DN");
    ui_object_set_themeable_style_property(ui_Label15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondUP1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_secondUP1, 30);
    lv_obj_set_height(ui_secondUP1, 35);
    lv_obj_set_x(ui_secondUP1, 68);
    lv_obj_set_y(ui_secondUP1, -15);
    lv_obj_set_align(ui_secondUP1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondUP1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondUP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondUP1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label16 = lv_label_create(ui_secondUP1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "UP");
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondDOWN1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_secondDOWN1, 30);
    lv_obj_set_height(ui_secondDOWN1, 35);
    lv_obj_set_x(ui_secondDOWN1, 101);
    lv_obj_set_y(ui_secondDOWN1, -15);
    lv_obj_set_align(ui_secondDOWN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondDOWN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondDOWN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondDOWN1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label17 = lv_label_create(ui_secondDOWN1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "DN");
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btnsavedate = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_btnsavedate, 100);
    lv_obj_set_height(ui_btnsavedate, 32);
    lv_obj_set_x(ui_btnsavedate, 0);
    lv_obj_set_y(ui_btnsavedate, 38);
    lv_obj_set_align(ui_btnsavedate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsavedate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnsavedate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btnsavedate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btnsavedate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label18 = lv_label_create(ui_btnsavedate);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "SAVE");
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btncancelChoose1 = lv_btn_create(ui_ContainerDate);
    lv_obj_set_width(ui_btncancelChoose1, 100);
    lv_obj_set_height(ui_btncancelChoose1, 32);
    lv_obj_set_x(ui_btncancelChoose1, 0);
    lv_obj_set_y(ui_btncancelChoose1, 80);
    lv_obj_set_align(ui_btncancelChoose1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncancelChoose1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncancelChoose1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btncancelChoose1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btncancelChoose1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label19 = lv_label_create(ui_btncancelChoose1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 2);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "CANCEL");
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_spinboxYear = lv_spinbox_create(ui_ContainerDate);
    lv_obj_set_width(ui_spinboxYear, 70);
    lv_obj_set_height(ui_spinboxYear, 42);
    lv_obj_set_x(ui_spinboxYear, 84);
    lv_obj_set_y(ui_spinboxYear, -58);
    lv_obj_set_align(ui_spinboxYear, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxYear, 2, 2);
    lv_spinbox_set_range(ui_spinboxYear, 0, 25);
    lv_spinbox_set_cursor_pos(ui_spinboxYear, 1 - 1);
    lv_spinbox_set_value(ui_spinboxYear, 2);
    ui_object_set_themeable_style_property(ui_spinboxYear, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxYear, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_spinboxMonth = lv_spinbox_create(ui_ContainerDate);
    lv_obj_set_width(ui_spinboxMonth, 70);
    lv_obj_set_height(ui_spinboxMonth, 42);
    lv_obj_set_x(ui_spinboxMonth, 0);
    lv_obj_set_y(ui_spinboxMonth, -58);
    lv_obj_set_align(ui_spinboxMonth, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxMonth, 2, 2);
    lv_spinbox_set_range(ui_spinboxMonth, 1, 12);
    lv_spinbox_set_cursor_pos(ui_spinboxMonth, 1 - 1);
    lv_spinbox_set_value(ui_spinboxMonth, 2);
    ui_object_set_themeable_style_property(ui_spinboxMonth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxMonth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_spinboxDay = lv_spinbox_create(ui_ContainerDate);
    lv_obj_set_width(ui_spinboxDay, 70);
    lv_obj_set_height(ui_spinboxDay, 42);
    lv_obj_set_x(ui_spinboxDay, -84);
    lv_obj_set_y(ui_spinboxDay, -58);
    lv_obj_set_align(ui_spinboxDay, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxDay, 2, 2);
    lv_spinbox_set_range(ui_spinboxDay, 1, 31);
    lv_spinbox_set_cursor_pos(ui_spinboxDay, 1 - 1);
    lv_spinbox_set_value(ui_spinboxDay, 2);
    ui_object_set_themeable_style_property(ui_spinboxDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_spinboxDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_ContainerTimeStatic = lv_obj_create(ui_dateAndtimeSCR);
    lv_obj_remove_style_all(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_ContainerTimeStatic, 314);
    lv_obj_set_height(ui_ContainerTimeStatic, 317);
    lv_obj_set_x(ui_ContainerTimeStatic, 0);
    lv_obj_set_y(ui_ContainerTimeStatic, 40);
    lv_obj_set_align(ui_ContainerTimeStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerTimeStatic, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerTimeStatic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourUP8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_hourUP8, 30);
    lv_obj_set_height(ui_hourUP8, 35);
    lv_obj_set_x(ui_hourUP8, -101);
    lv_obj_set_y(ui_hourUP8, -15);
    lv_obj_set_align(ui_hourUP8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourUP8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourUP8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label76 = lv_label_create(ui_hourUP8);
    lv_obj_set_width(ui_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label76, -1);
    lv_obj_set_y(ui_Label76, 0);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label76, "UP");
    ui_object_set_themeable_style_property(ui_Label76, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label76, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_hourDOWN8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_hourDOWN8, 30);
    lv_obj_set_height(ui_hourDOWN8, 35);
    lv_obj_set_x(ui_hourDOWN8, -67);
    lv_obj_set_y(ui_hourDOWN8, -15);
    lv_obj_set_align(ui_hourDOWN8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourDOWN8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourDOWN8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label77 = lv_label_create(ui_hourDOWN8);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "DN");
    ui_object_set_themeable_style_property(ui_Label77, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label77, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteUP8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_minuteUP8, 30);
    lv_obj_set_height(ui_minuteUP8, 35);
    lv_obj_set_x(ui_minuteUP8, -17);
    lv_obj_set_y(ui_minuteUP8, -15);
    lv_obj_set_align(ui_minuteUP8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteUP8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteUP8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label69 = lv_label_create(ui_minuteUP8);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "UP");
    ui_object_set_themeable_style_property(ui_Label69, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label69, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteDOWN8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_minuteDOWN8, 30);
    lv_obj_set_height(ui_minuteDOWN8, 35);
    lv_obj_set_x(ui_minuteDOWN8, 16);
    lv_obj_set_y(ui_minuteDOWN8, -15);
    lv_obj_set_align(ui_minuteDOWN8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteDOWN8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteDOWN8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label70 = lv_label_create(ui_minuteDOWN8);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "DN");
    ui_object_set_themeable_style_property(ui_Label70, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label70, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondUP8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_secondUP8, 30);
    lv_obj_set_height(ui_secondUP8, 35);
    lv_obj_set_x(ui_secondUP8, 68);
    lv_obj_set_y(ui_secondUP8, -15);
    lv_obj_set_align(ui_secondUP8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondUP8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondUP8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondUP8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label71 = lv_label_create(ui_secondUP8);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "UP");
    ui_object_set_themeable_style_property(ui_Label71, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label71, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondDOWN8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_secondDOWN8, 30);
    lv_obj_set_height(ui_secondDOWN8, 35);
    lv_obj_set_x(ui_secondDOWN8, 101);
    lv_obj_set_y(ui_secondDOWN8, -15);
    lv_obj_set_align(ui_secondDOWN8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondDOWN8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondDOWN8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondDOWN8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label72 = lv_label_create(ui_secondDOWN8);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "DN");
    ui_object_set_themeable_style_property(ui_Label72, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label72, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btnsavetime4 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_btnsavetime4, 100);
    lv_obj_set_height(ui_btnsavetime4, 32);
    lv_obj_set_x(ui_btnsavetime4, 80);
    lv_obj_set_y(ui_btnsavetime4, 38);
    lv_obj_set_align(ui_btnsavetime4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsavetime4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnsavetime4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btnsavetime4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btnsavetime4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label73 = lv_label_create(ui_btnsavetime4);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "NEXT");
    ui_object_set_themeable_style_property(ui_Label73, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label73, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btncancelChoose8 = lv_btn_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_btncancelChoose8, 100);
    lv_obj_set_height(ui_btncancelChoose8, 32);
    lv_obj_set_x(ui_btncancelChoose8, -80);
    lv_obj_set_y(ui_btncancelChoose8, 38);
    lv_obj_set_align(ui_btncancelChoose8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncancelChoose8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncancelChoose8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btncancelChoose8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btncancelChoose8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label74 = lv_label_create(ui_btncancelChoose8);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, 0);
    lv_obj_set_y(ui_Label74, 2);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "CANCEL");
    ui_object_set_themeable_style_property(ui_Label74, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label74, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_startSecond = lv_spinbox_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_startSecond, 70);
    lv_obj_set_height(ui_startSecond, 42);
    lv_obj_set_x(ui_startSecond, 84);
    lv_obj_set_y(ui_startSecond, -58);
    lv_obj_set_align(ui_startSecond, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startSecond, 2, 2);
    lv_spinbox_set_range(ui_startSecond, 0, 59);
    lv_spinbox_set_cursor_pos(ui_startSecond, 1 - 1);
    lv_spinbox_set_value(ui_startSecond, 2);
    ui_object_set_themeable_style_property(ui_startSecond, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startSecond, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_startMinute = lv_spinbox_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_startMinute, 70);
    lv_obj_set_height(ui_startMinute, 42);
    lv_obj_set_x(ui_startMinute, 0);
    lv_obj_set_y(ui_startMinute, -58);
    lv_obj_set_align(ui_startMinute, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startMinute, 2, 2);
    lv_spinbox_set_range(ui_startMinute, 0, 59);
    lv_spinbox_set_cursor_pos(ui_startMinute, 1 - 1);
    lv_spinbox_set_value(ui_startMinute, 2);
    ui_object_set_themeable_style_property(ui_startMinute, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startMinute, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_startHour = lv_spinbox_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_startHour, 70);
    lv_obj_set_height(ui_startHour, 42);
    lv_obj_set_x(ui_startHour, -84);
    lv_obj_set_y(ui_startHour, -58);
    lv_obj_set_align(ui_startHour, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startHour, 2, 2);
    lv_spinbox_set_range(ui_startHour, 1, 12);
    lv_spinbox_set_cursor_pos(ui_startHour, 1 - 1);
    lv_spinbox_set_value(ui_startHour, 2);
    ui_object_set_themeable_style_property(ui_startHour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startHour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_Label68 = lv_label_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, 1);
    lv_obj_set_y(ui_Label68, -140);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "Initial time & date of the required period:\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");

    ui_lableTimeChange1 = lv_label_create(ui_ContainerTimeStatic);
    lv_obj_set_width(ui_lableTimeChange1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableTimeChange1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableTimeChange1, -21);
    lv_obj_set_y(ui_lableTimeChange1, -105);
    lv_obj_set_align(ui_lableTimeChange1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableTimeChange1,
                      "             HOURS       MINUTES     SECONDS\n           ------------      ---------------    --------------");

    ui_ContainerDateStatic = lv_obj_create(ui_dateAndtimeSCR);
    lv_obj_remove_style_all(ui_ContainerDateStatic);
    lv_obj_set_width(ui_ContainerDateStatic, 314);
    lv_obj_set_height(ui_ContainerDateStatic, 317);
    lv_obj_set_x(ui_ContainerDateStatic, 0);
    lv_obj_set_y(ui_ContainerDateStatic, 40);
    lv_obj_set_align(ui_ContainerDateStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerDateStatic, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerDateStatic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourUP9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_hourUP9, 30);
    lv_obj_set_height(ui_hourUP9, 35);
    lv_obj_set_x(ui_hourUP9, -101);
    lv_obj_set_y(ui_hourUP9, -15);
    lv_obj_set_align(ui_hourUP9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourUP9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourUP9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label75 = lv_label_create(ui_hourUP9);
    lv_obj_set_width(ui_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label75, -1);
    lv_obj_set_y(ui_Label75, 0);
    lv_obj_set_align(ui_Label75, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label75, "UP");
    ui_object_set_themeable_style_property(ui_Label75, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label75, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_hourDOWN9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_hourDOWN9, 30);
    lv_obj_set_height(ui_hourDOWN9, 35);
    lv_obj_set_x(ui_hourDOWN9, -67);
    lv_obj_set_y(ui_hourDOWN9, -15);
    lv_obj_set_align(ui_hourDOWN9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourDOWN9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hourDOWN9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_hourDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_hourDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label78 = lv_label_create(ui_hourDOWN9);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "DN");
    ui_object_set_themeable_style_property(ui_Label78, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label78, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteUP9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_minuteUP9, 30);
    lv_obj_set_height(ui_minuteUP9, 35);
    lv_obj_set_x(ui_minuteUP9, -17);
    lv_obj_set_y(ui_minuteUP9, -15);
    lv_obj_set_align(ui_minuteUP9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteUP9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteUP9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label79 = lv_label_create(ui_minuteUP9);
    lv_obj_set_width(ui_Label79, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label79, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label79, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label79, "UP");
    ui_object_set_themeable_style_property(ui_Label79, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label79, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_minuteDOWN9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_minuteDOWN9, 30);
    lv_obj_set_height(ui_minuteDOWN9, 35);
    lv_obj_set_x(ui_minuteDOWN9, 16);
    lv_obj_set_y(ui_minuteDOWN9, -15);
    lv_obj_set_align(ui_minuteDOWN9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minuteDOWN9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minuteDOWN9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_minuteDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_minuteDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label80 = lv_label_create(ui_minuteDOWN9);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label80, "DN");
    ui_object_set_themeable_style_property(ui_Label80, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label80, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondUP9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_secondUP9, 30);
    lv_obj_set_height(ui_secondUP9, 35);
    lv_obj_set_x(ui_secondUP9, 68);
    lv_obj_set_y(ui_secondUP9, -15);
    lv_obj_set_align(ui_secondUP9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondUP9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondUP9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondUP9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label81 = lv_label_create(ui_secondUP9);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label81, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label81, "UP");
    ui_object_set_themeable_style_property(ui_Label81, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label81, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_secondDOWN9 = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_secondDOWN9, 30);
    lv_obj_set_height(ui_secondDOWN9, 35);
    lv_obj_set_x(ui_secondDOWN9, 101);
    lv_obj_set_y(ui_secondDOWN9, -15);
    lv_obj_set_align(ui_secondDOWN9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_secondDOWN9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_secondDOWN9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_secondDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_secondDOWN9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label82 = lv_label_create(ui_secondDOWN9);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label82, "DN");
    ui_object_set_themeable_style_property(ui_Label82, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label82, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btnsavedateStatic = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_btnsavedateStatic, 100);
    lv_obj_set_height(ui_btnsavedateStatic, 32);
    lv_obj_set_x(ui_btnsavedateStatic, 80);
    lv_obj_set_y(ui_btnsavedateStatic, 38);
    lv_obj_set_align(ui_btnsavedateStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsavedateStatic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnsavedateStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btnsavedateStatic, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btnsavedateStatic, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label83 = lv_label_create(ui_btnsavedateStatic);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "SAVE");
    ui_object_set_themeable_style_property(ui_Label83, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label83, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_btncancelChooseStatic = lv_btn_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_btncancelChooseStatic, 100);
    lv_obj_set_height(ui_btncancelChooseStatic, 32);
    lv_obj_set_x(ui_btncancelChooseStatic, -80);
    lv_obj_set_y(ui_btncancelChooseStatic, 38);
    lv_obj_set_align(ui_btncancelChooseStatic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btncancelChooseStatic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btncancelChooseStatic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_btncancelChooseStatic, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_btncancelChooseStatic, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_white);

    ui_Label84 = lv_label_create(ui_btncancelChooseStatic);
    lv_obj_set_width(ui_Label84, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label84, 0);
    lv_obj_set_y(ui_Label84, 2);
    lv_obj_set_align(ui_Label84, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label84, "CANCEL");
    ui_object_set_themeable_style_property(ui_Label84, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_Label84, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_black);

    ui_startYear = lv_spinbox_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_startYear, 70);
    lv_obj_set_height(ui_startYear, 42);
    lv_obj_set_x(ui_startYear, 84);
    lv_obj_set_y(ui_startYear, -58);
    lv_obj_set_align(ui_startYear, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startYear, 2, 2);
    lv_spinbox_set_range(ui_startYear, 0, 25);
    lv_spinbox_set_cursor_pos(ui_startYear, 1 - 1);
    lv_spinbox_set_value(ui_startYear, 2);
    ui_object_set_themeable_style_property(ui_startYear, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startYear, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_startMonth = lv_spinbox_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_startMonth, 70);
    lv_obj_set_height(ui_startMonth, 42);
    lv_obj_set_x(ui_startMonth, 0);
    lv_obj_set_y(ui_startMonth, -58);
    lv_obj_set_align(ui_startMonth, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startMonth, 2, 2);
    lv_spinbox_set_range(ui_startMonth, 1, 12);
    lv_spinbox_set_cursor_pos(ui_startMonth, 1 - 1);
    lv_spinbox_set_value(ui_startMonth, 2);
    ui_object_set_themeable_style_property(ui_startMonth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startMonth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_startDay = lv_spinbox_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_startDay, 70);
    lv_obj_set_height(ui_startDay, 42);
    lv_obj_set_x(ui_startDay, -84);
    lv_obj_set_y(ui_startDay, -58);
    lv_obj_set_align(ui_startDay, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_startDay, 2, 2);
    lv_spinbox_set_range(ui_startDay, 0, 31);
    lv_spinbox_set_cursor_pos(ui_startDay, 1 - 1);
    lv_spinbox_set_value(ui_startDay, 0);
    ui_object_set_themeable_style_property(ui_startDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_startDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);

    ui_Label85 = lv_label_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_Label85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label85, 1);
    lv_obj_set_y(ui_Label85, -140);
    lv_obj_set_align(ui_Label85, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label85, "Initial time & date of the required period:\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");

    ui_lableDateChange4 = lv_label_create(ui_ContainerDateStatic);
    lv_obj_set_width(ui_lableDateChange4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableDateChange4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableDateChange4, 0);
    lv_obj_set_y(ui_lableDateChange4, -94);
    lv_obj_set_align(ui_lableDateChange4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableDateChange4,
                      "  DAY          MONTH         YEAR\n---------        ------------      -----------");

    lv_obj_add_event_cb(ui_timeOK, ui_event_timeOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dateOK, ui_event_dateOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeAndDateCANCEL, ui_event_timeAndDateCANCEL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourUP, ui_event_hourUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourDOWN, ui_event_hourDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteUP, ui_event_minuteUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteDOWN, ui_event_minuteDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondUP, ui_event_secondUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondDOWN, ui_event_secondDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnsavetime, ui_event_btnsavetime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncancelChoose, ui_event_btncancelChoose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourUP1, ui_event_hourUP1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourDOWN1, ui_event_hourDOWN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteUP1, ui_event_minuteUP1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteDOWN1, ui_event_minuteDOWN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondUP1, ui_event_secondUP1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondDOWN1, ui_event_secondDOWN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnsavedate, ui_event_btnsavedate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncancelChoose1, ui_event_btncancelChoose1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourUP8, ui_event_hourUP8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourDOWN8, ui_event_hourDOWN8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteUP8, ui_event_minuteUP8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteDOWN8, ui_event_minuteDOWN8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondUP8, ui_event_secondUP8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondDOWN8, ui_event_secondDOWN8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnsavetime4, ui_event_btnsavetime4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncancelChoose8, ui_event_btncancelChoose8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourUP9, ui_event_hourUP9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hourDOWN9, ui_event_hourDOWN9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteUP9, ui_event_minuteUP9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minuteDOWN9, ui_event_minuteDOWN9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondUP9, ui_event_secondUP9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_secondDOWN9, ui_event_secondDOWN9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnsavedateStatic, ui_event_btnsavedateStatic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btncancelChooseStatic, ui_event_btncancelChooseStatic, LV_EVENT_ALL, NULL);

}
