// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void amTochange(lv_event_t * e);
void pmTochange(lv_event_t * e);
void tempArch_need_flag(lv_event_t * e);
void timeChangeHandler(lv_event_t * e);
void dateChangeHandler(lv_event_t * e);
void save_time_event(lv_event_t * e);
void save_date_event(lv_event_t * e);
void init_static_time_save(lv_event_t * e);
void init_static_date_save(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
