// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_chart_series_t * ui_humidCH_series_1 = NULL;

void ui_humidSCR_screen_init(void)
{
    ui_humidSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_humidSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_humidSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_humidSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);
    ui_object_set_themeable_style_property(ui_humidSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_black);
    lv_obj_set_style_bg_grad_dir(ui_humidSCR, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidCH = lv_chart_create(ui_humidSCR);
    lv_obj_set_width(ui_humidCH, 250);
    lv_obj_set_height(ui_humidCH, 144);
    lv_obj_set_x(ui_humidCH, 15);
    lv_obj_set_y(ui_humidCH, -10);
    lv_obj_set_align(ui_humidCH, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_humidCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_humidCH, 30);
    lv_chart_set_range(ui_humidCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_humidCH, 20, 20);
    lv_chart_set_zoom_x(ui_humidCH, 512);
    lv_chart_set_zoom_y(ui_humidCH, 256);
    lv_chart_set_axis_tick(ui_humidCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_humidCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_set_axis_tick(ui_humidCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_humidCH_series_1 = lv_chart_add_series(ui_humidCH, lv_color_hex(0xEBEBEB),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_humidCH_series_1_array[] = { 0, 10, 20, 40, 80, 100, 100, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_humidCH, ui_humidCH_series_1, ui_humidCH_series_1_array);
    ui_object_set_themeable_style_property(ui_humidCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_humidCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_humidCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_humidCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_humidCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_humidCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_humidCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_humidCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_pageCNT2 = lv_label_create(ui_humidSCR);
    lv_obj_set_width(ui_pageCNT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pageCNT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pageCNT2, 0);
    lv_obj_set_y(ui_pageCNT2, 100);
    lv_obj_set_align(ui_pageCNT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pageCNT2, "2 - HUMIDITY - %");

    ui_valHumidSCR2 = lv_label_create(ui_humidSCR);
    lv_obj_set_width(ui_valHumidSCR2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valHumidSCR2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valHumidSCR2, 0);
    lv_obj_set_y(ui_valHumidSCR2, -103);
    lv_obj_set_align(ui_valHumidSCR2, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_humidSCR);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -92);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "---------------------------");

    ui_humidStaticCH = lv_chart_create(ui_humidSCR);
    lv_obj_set_width(ui_humidStaticCH, 250);
    lv_obj_set_height(ui_humidStaticCH, 144);
    lv_obj_set_x(ui_humidStaticCH, 15);
    lv_obj_set_y(ui_humidStaticCH, -10);
    lv_obj_set_align(ui_humidStaticCH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidStaticCH, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_humidStaticCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_humidStaticCH, 30);
    lv_chart_set_range(ui_humidStaticCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_humidStaticCH, 20, 20);
    lv_chart_set_axis_tick(ui_humidStaticCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_humidStaticCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_set_axis_tick(ui_humidStaticCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_humidStaticCH_series_1 = lv_chart_add_series(ui_humidStaticCH, lv_color_hex(0xEBEBEB),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_humidStaticCH_series_1_array[] = { 0, 10, 20, 40, 80, 100, 100, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_humidStaticCH, ui_humidStaticCH_series_1, ui_humidStaticCH_series_1_array);
    ui_object_set_themeable_style_property(ui_humidStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_humidStaticCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_humidStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_humidStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_humidStaticCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_humidStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_humidStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_humidStaticCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_HumidStaticPeriod = lv_label_create(ui_humidSCR);
    lv_obj_set_width(ui_HumidStaticPeriod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidStaticPeriod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidStaticPeriod, 95);
    lv_obj_set_y(ui_HumidStaticPeriod, -103);
    lv_obj_set_align(ui_HumidStaticPeriod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidStaticPeriod, "PERIOD:");
    lv_obj_add_flag(ui_HumidStaticPeriod, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_humidArchive = lv_btn_create(ui_humidSCR);
    lv_obj_set_width(ui_humidArchive, 62);
    lv_obj_set_height(ui_humidArchive, 26);
    lv_obj_set_x(ui_humidArchive, -121);
    lv_obj_set_y(ui_humidArchive, -103);
    lv_obj_set_align(ui_humidArchive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humidArchive, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_humidArchive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_humidArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_humidArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    ui_Label22 = lv_label_create(ui_humidArchive);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Archive");

    lv_obj_add_event_cb(ui_humidArchive, ui_event_humidArchive, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_humidSCR, ui_event_humidSCR, LV_EVENT_ALL, NULL);

}
