// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_main, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_main, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_blue);
    ui_object_set_themeable_style_property(ui_main, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_black);
    lv_obj_set_style_bg_grad_dir(ui_main, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator = lv_label_create(ui_main);
    lv_obj_set_width(ui_separator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_separator, 0);
    lv_obj_set_y(ui_separator, -95);
    lv_obj_set_align(ui_separator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator, "|");

    ui_tempMain = lv_label_create(ui_main);
    lv_obj_set_width(ui_tempMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempMain, 0);
    lv_obj_set_y(ui_tempMain, -40);
    lv_obj_set_align(ui_tempMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempMain, "T");

    ui_rhMain = lv_label_create(ui_main);
    lv_obj_set_width(ui_rhMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rhMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rhMain, -70);
    lv_obj_set_y(ui_rhMain, 30);
    lv_obj_set_align(ui_rhMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rhMain, "RH:");

    ui_pMain = lv_label_create(ui_main);
    lv_obj_set_width(ui_pMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pMain, 70);
    lv_obj_set_y(ui_pMain, 30);
    lv_obj_set_align(ui_pMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pMain, "P:");

    ui_pageCNT0 = lv_label_create(ui_main);
    lv_obj_set_width(ui_pageCNT0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pageCNT0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pageCNT0, 0);
    lv_obj_set_y(ui_pageCNT0, 90);
    lv_obj_set_align(ui_pageCNT0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pageCNT0, "0 - MAIN");

    ui_labeltimeformat = lv_label_create(ui_main);
    lv_obj_set_width(ui_labeltimeformat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labeltimeformat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labeltimeformat, -27);
    lv_obj_set_y(ui_labeltimeformat, -94);
    lv_obj_set_align(ui_labeltimeformat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltimeformat, "TF");

    ui_tfChangeBTN = lv_btn_create(ui_main);
    lv_obj_set_width(ui_tfChangeBTN, 35);
    lv_obj_set_height(ui_tfChangeBTN, 21);
    lv_obj_set_x(ui_tfChangeBTN, -28);
    lv_obj_set_y(ui_tfChangeBTN, -97);
    lv_obj_set_align(ui_tfChangeBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tfChangeBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tfChangeBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tfChangeBTN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tfChangeBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_popuptimeformat = lv_obj_create(ui_main);
    lv_obj_remove_style_all(ui_popuptimeformat);
    lv_obj_set_width(ui_popuptimeformat, 221);
    lv_obj_set_height(ui_popuptimeformat, 123);
    lv_obj_set_x(ui_popuptimeformat, 7);
    lv_obj_set_y(ui_popuptimeformat, -8);
    lv_obj_set_align(ui_popuptimeformat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_popuptimeformat, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_popuptimeformat, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_amFormat = lv_btn_create(ui_popuptimeformat);
    lv_obj_set_width(ui_amFormat, 50);
    lv_obj_set_height(ui_amFormat, 30);
    lv_obj_set_x(ui_amFormat, -70);
    lv_obj_set_y(ui_amFormat, -50);
    lv_obj_set_align(ui_amFormat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_amFormat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_amFormat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_amFormat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_amFormat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_black);

    ui_AMlabel = lv_label_create(ui_amFormat);
    lv_obj_set_width(ui_AMlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AMlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AMlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AMlabel, "AM");

    ui_pmFormat = lv_btn_create(ui_popuptimeformat);
    lv_obj_set_width(ui_pmFormat, 50);
    lv_obj_set_height(ui_pmFormat, 30);
    lv_obj_set_x(ui_pmFormat, 0);
    lv_obj_set_y(ui_pmFormat, -50);
    lv_obj_set_align(ui_pmFormat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pmFormat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pmFormat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pmFormat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_pmFormat, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_black);

    ui_PMlabel = lv_label_create(ui_pmFormat);
    lv_obj_set_width(ui_PMlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PMlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PMlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PMlabel, "PM");

    ui_timeButton = lv_btn_create(ui_main);
    lv_obj_set_width(ui_timeButton, 115);
    lv_obj_set_height(ui_timeButton, 35);
    lv_obj_set_x(ui_timeButton, -100);
    lv_obj_set_y(ui_timeButton, -94);
    lv_obj_set_align(ui_timeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_timeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lableTime = lv_label_create(ui_main);
    lv_obj_set_width(ui_lableTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableTime, -102);
    lv_obj_set_y(ui_lableTime, -94);
    lv_obj_set_align(ui_lableTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableTime, "time");

    ui_lableDate = lv_label_create(ui_main);
    lv_obj_set_width(ui_lableDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lableDate, 77);
    lv_obj_set_y(ui_lableDate, -94);
    lv_obj_set_align(ui_lableDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableDate, "date");

    ui_dateButton = lv_btn_create(ui_main);
    lv_obj_set_width(ui_dateButton, 138);
    lv_obj_set_height(ui_dateButton, 50);
    lv_obj_set_x(ui_dateButton, 83);
    lv_obj_set_y(ui_dateButton, -91);
    lv_obj_set_align(ui_dateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dateButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tfChangeBTN, ui_event_tfChangeBTN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amFormat, ui_event_amFormat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pmFormat, ui_event_pmFormat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeButton, ui_event_timeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dateButton, ui_event_dateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}
