// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_chart_series_t * ui_pressCH_series_1 = NULL;

void ui_pressSCR_screen_init(void)
{
    ui_pressSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pressSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pressSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_pressSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);
    ui_object_set_themeable_style_property(ui_pressSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_black);
    lv_obj_set_style_bg_grad_dir(ui_pressSCR, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressCH = lv_chart_create(ui_pressSCR);
    lv_obj_set_width(ui_pressCH, 250);
    lv_obj_set_height(ui_pressCH, 144);
    lv_obj_set_x(ui_pressCH, 15);
    lv_obj_set_y(ui_pressCH, -10);
    lv_obj_set_align(ui_pressCH, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_pressCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_pressCH, 30);
    lv_chart_set_range(ui_pressCH, LV_CHART_AXIS_PRIMARY_Y, 0, 2000);
    lv_chart_set_range(ui_pressCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_pressCH, 20, 20);
    lv_chart_set_zoom_x(ui_pressCH, 512);
    lv_chart_set_zoom_y(ui_pressCH, 256);
    lv_chart_set_axis_tick(ui_pressCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_pressCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_pressCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_pressCH_series_1 = lv_chart_add_series(ui_pressCH, lv_color_hex(0xEBEBEB),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_pressCH_series_1_array[] = { 0, 500, 1000, 1500, 2000, 2000, 1500, 1000, 500, 0 };
    lv_chart_set_ext_y_array(ui_pressCH, ui_pressCH_series_1, ui_pressCH_series_1_array);
    ui_object_set_themeable_style_property(ui_pressCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_pressCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pressCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_pressCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_pressCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_pressCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_pressCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_pressCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_pageCNT3 = lv_label_create(ui_pressSCR);
    lv_obj_set_width(ui_pageCNT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pageCNT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pageCNT3, 0);
    lv_obj_set_y(ui_pageCNT3, 100);
    lv_obj_set_align(ui_pageCNT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pageCNT3, "3 - PRESSURE - hPa");

    ui_valPressSCR3 = lv_label_create(ui_pressSCR);
    lv_obj_set_width(ui_valPressSCR3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valPressSCR3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valPressSCR3, 0);
    lv_obj_set_y(ui_valPressSCR3, -103);
    lv_obj_set_align(ui_valPressSCR3, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_pressSCR);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -92);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "---------------------------");

    ui_pressStaticCH = lv_chart_create(ui_pressSCR);
    lv_obj_set_width(ui_pressStaticCH, 250);
    lv_obj_set_height(ui_pressStaticCH, 144);
    lv_obj_set_x(ui_pressStaticCH, 15);
    lv_obj_set_y(ui_pressStaticCH, -10);
    lv_obj_set_align(ui_pressStaticCH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pressStaticCH, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_chart_set_type(ui_pressStaticCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_pressStaticCH, 30);
    lv_chart_set_range(ui_pressStaticCH, LV_CHART_AXIS_PRIMARY_Y, 0, 2000);
    lv_chart_set_range(ui_pressStaticCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_pressStaticCH, 20, 20);
    lv_chart_set_axis_tick(ui_pressStaticCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_pressStaticCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_pressStaticCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_pressStaticCH_series_1 = lv_chart_add_series(ui_pressStaticCH, lv_color_hex(0xEBEBEB),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_pressStaticCH_series_1_array[] = { 0, 500, 1000, 1500, 2000, 2000, 1500, 1000, 500, 0 };
    lv_chart_set_ext_y_array(ui_pressStaticCH, ui_pressStaticCH_series_1, ui_pressStaticCH_series_1_array);
    ui_object_set_themeable_style_property(ui_pressStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_pressStaticCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_pressStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_pressStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_pressStaticCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_pressStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_pressStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_pressStaticCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_PressStaticPeriod = lv_label_create(ui_pressSCR);
    lv_obj_set_width(ui_PressStaticPeriod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressStaticPeriod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressStaticPeriod, 95);
    lv_obj_set_y(ui_PressStaticPeriod, -103);
    lv_obj_set_align(ui_PressStaticPeriod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressStaticPeriod, "PERIOD:");
    lv_obj_add_flag(ui_PressStaticPeriod, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_pressArchive = lv_btn_create(ui_pressSCR);
    lv_obj_set_width(ui_pressArchive, 62);
    lv_obj_set_height(ui_pressArchive, 26);
    lv_obj_set_x(ui_pressArchive, -121);
    lv_obj_set_y(ui_pressArchive, -103);
    lv_obj_set_align(ui_pressArchive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pressArchive, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pressArchive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_pressArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_pressArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    ui_Label21 = lv_label_create(ui_pressArchive);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Archive");

    lv_obj_add_event_cb(ui_pressArchive, ui_event_pressArchive, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pressSCR, ui_event_pressSCR, LV_EVENT_ALL, NULL);

}
