// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_blue[1] = {0x3D5684};
const ui_theme_variable_t _ui_theme_alpha_blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_white[1] = {0xB1B2BA};
const ui_theme_variable_t _ui_theme_alpha_white[1] = {255};

const ui_theme_variable_t _ui_theme_color_purple[1] = {0x67546E};
const ui_theme_variable_t _ui_theme_alpha_purple[1] = {255};

const ui_theme_variable_t _ui_theme_color_azure[1] = {0x4B7977};
const ui_theme_variable_t _ui_theme_alpha_azure[1] = {255};

const ui_theme_variable_t _ui_theme_color_black[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_black[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

