// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_chart_series_t * ui_tempStaticCH_series_1 = NULL;

void ui_tempSCR_screen_init(void)
{
    ui_tempSCR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tempSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_tempSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_blue);
    ui_object_set_themeable_style_property(ui_tempSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_blue);
    ui_object_set_themeable_style_property(ui_tempSCR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_black);
    lv_obj_set_style_bg_grad_dir(ui_tempSCR, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempCH = lv_chart_create(ui_tempSCR);
    lv_obj_set_width(ui_tempCH, 250);
    lv_obj_set_height(ui_tempCH, 144);
    lv_obj_set_x(ui_tempCH, 15);
    lv_obj_set_y(ui_tempCH, -10);
    lv_obj_set_align(ui_tempCH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempCH, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_chart_set_type(ui_tempCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_tempCH, 30);
    lv_chart_set_range(ui_tempCH, LV_CHART_AXIS_PRIMARY_Y, -5, 30);
    lv_chart_set_div_line_count(ui_tempCH, 20, 20);
    lv_chart_set_zoom_x(ui_tempCH, 512);
    lv_chart_set_zoom_y(ui_tempCH, 256);
    lv_chart_set_axis_tick(ui_tempCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 7, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_chart_series_t * ui_tempCH_series_1 = lv_chart_add_series(ui_tempCH, lv_color_hex(0xEBEBEB),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_tempCH_series_1_array[] = { 0, 10, 20, 25, 30, 30, 25, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_tempCH, ui_tempCH_series_1, ui_tempCH_series_1_array);
    ui_object_set_themeable_style_property(ui_tempCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_tempCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_tempCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_tempCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_tempCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_tempCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_tempCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_tempCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_pageCNT1 = lv_label_create(ui_tempSCR);
    lv_obj_set_width(ui_pageCNT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pageCNT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pageCNT1, 0);
    lv_obj_set_y(ui_pageCNT1, 100);
    lv_obj_set_align(ui_pageCNT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pageCNT1, "1 - TEMPERATURE - °C");

    ui_valTempSCR1 = lv_label_create(ui_tempSCR);
    lv_obj_set_width(ui_valTempSCR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_valTempSCR1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_valTempSCR1, 0);
    lv_obj_set_y(ui_valTempSCR1, -103);
    lv_obj_set_align(ui_valTempSCR1, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_tempSCR);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -92);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "---------------------------");

    ui_tempStaticCH = lv_chart_create(ui_tempSCR);
    lv_obj_set_width(ui_tempStaticCH, 250);
    lv_obj_set_height(ui_tempStaticCH, 144);
    lv_obj_set_x(ui_tempStaticCH, 15);
    lv_obj_set_y(ui_tempStaticCH, -16);
    lv_obj_set_align(ui_tempStaticCH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempStaticCH, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_chart_set_type(ui_tempStaticCH, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_tempStaticCH, 30);
    lv_chart_set_range(ui_tempStaticCH, LV_CHART_AXIS_PRIMARY_Y, -5, 30);
    lv_chart_set_div_line_count(ui_tempStaticCH, 20, 20);
    lv_chart_set_axis_tick(ui_tempStaticCH, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempStaticCH, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 7, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempStaticCH, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_tempStaticCH_series_1 = lv_chart_add_series(ui_tempStaticCH, lv_color_hex(0xEBEBEB),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_tempStaticCH_series_1_array[] = { 0, 10, 20, 25, 30, 30, 25, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_tempStaticCH, ui_tempStaticCH_series_1, ui_tempStaticCH_series_1_array);
    ui_object_set_themeable_style_property(ui_tempStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_blue);
    lv_obj_set_style_bg_grad_dir(ui_tempStaticCH, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_tempStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR,
                                           _ui_theme_color_black);
    ui_object_set_themeable_style_property(ui_tempStaticCH, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_LINE_OPA,
                                           _ui_theme_alpha_black);
    lv_obj_set_style_line_width(ui_tempStaticCH, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_tempStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_tempStaticCH, LV_PART_SCROLLBAR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    lv_obj_set_style_line_width(ui_tempStaticCH, 2, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_TempStaticPeriod = lv_label_create(ui_tempSCR);
    lv_obj_set_width(ui_TempStaticPeriod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempStaticPeriod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempStaticPeriod, 95);
    lv_obj_set_y(ui_TempStaticPeriod, -103);
    lv_obj_set_align(ui_TempStaticPeriod, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempStaticPeriod, "PERIOD:");
    lv_obj_add_flag(ui_TempStaticPeriod, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_tempArchive = lv_btn_create(ui_tempSCR);
    lv_obj_set_width(ui_tempArchive, 62);
    lv_obj_set_height(ui_tempArchive, 26);
    lv_obj_set_x(ui_tempArchive, -121);
    lv_obj_set_y(ui_tempArchive, -103);
    lv_obj_set_align(ui_tempArchive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempArchive, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tempArchive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_tempArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_purple);
    ui_object_set_themeable_style_property(ui_tempArchive, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_purple);

    ui_Label20 = lv_label_create(ui_tempArchive);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Archive");

    lv_obj_add_event_cb(ui_tempArchive, ui_event_tempArchive, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempSCR, ui_event_tempSCR, LV_EVENT_ALL, NULL);

}
